import React, { Component } from 'react';
import './styles/app/App.css';

class App extends Component {
  constructor(props) {
    super(props);
    
    this.state = {
      urlsFrom: [],
      urlsTo: [],
      result: ''
    }
  }

  changeUrlFrom = (event) => {
    this.setState({urlsFrom: this.parseStringToArray(event.target.value)});
  }

  changeUrlTo = (event) => {
    this.setState({urlsTo: this.parseStringToArray(event.target.value)});
  }

  parseStringToArray = (urlString) => {
    return urlString.split('\n');
  }

  redirectUrls = (urlsFrom, urlsTo) => {
    const len = urlsFrom.length;
    let result = '#Generated by DevWichrowski Redirections\n';
    
    for (let i = 0; i < len; i++) {
      result += `RewriteRule ^${urlsFrom[i]}$ ^${urlsTo[i]}$ [R=301,L]\n`;
    }

    return result;
  }

  generateUrl = () => {
    console.log(this.state);
      this.setState({
        result: this.redirectUrls(this.state.urlsFrom, this.state.urlsTo)
      });
  }

  render() {
    return (
      <div className="wrapper">
        <div className='redirects'>
          <textarea className='push-left text-box form-control' onChange={this.changeUrlFrom}/>
          <textarea  className='push-right text-box form-control' onChange={this.changeUrlTo}/>
        </div>
        <button className='center-item btn btn-secondary' onClick = {this.generateUrl}>Generuj</button>
        <textarea className='full-width form-control' placeholder='WYNIK' value={this.state.result} readOnly={true}/>
      </div>
    );
  }
}

export default App;
